;; Conglomo's Spell Expander (2013.03.04)

/purgedef spell_[0-9]*
/def -Fp5 -P1 -mregexp -t"'(Mhael)'" spell_1 = /substitute -p -- %{PL}%{P0} [@{B}absent mind@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(yluigh bugh)'" spell_2 = /substitute -p -- %{PL}%{P0} [@{B}acid arrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio thorex acid)'" spell_3 = /substitute -p -- %{PL}%{P0} [@{B}acid blade@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(raza suoruflus)'" spell_4 = /substitute -p -- %{PL}%{P0} [@{B}acid blast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dhazzzziii khorrozzz dhemicus)'" spell_5 = /substitute -p -- %{PL}%{P0} [@{B}acid fangs@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn burnn arse)'" spell_6 = /substitute -p -- %{PL}%{P0} [@{B}acid preference@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(Stelm suoreflus umb enog)'" spell_7 = /substitute -p -- %{PL}%{P0} [@{B}acid rain@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(norbitz burnn arse)'" spell_8 = /substitute -p -- %{PL}%{P0} [@{B}acid vulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(u ma dayer ot vednaca)'" spell_9 = /substitute -p -- %{PL}%{P0} [@{B}advancement@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ZipZap)'" spell_10 = /substitute -p -- %{PL}%{P0} [@{B}agility boost@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(braaazt brizzzt)'" spell_11 = /substitute -p -- %{PL}%{P0} [@{B}alarm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Erofeb Naht Ssel)'" spell_12 = /substitute -p -- %{PL}%{P0} [@{B}all pain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(DOH!)'" spell_13 = /substitute -p -- %{PL}%{P0} [@{B}amnesia@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(YaaaaAAAA Zhu)'" spell_14 = /substitute -p -- %{PL}%{P0} [@{B}amorphic armour@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Aduraa rais rais undeadis)'" spell_15 = /substitute -p -- %{PL}%{P0} [@{B}animate dead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ykal ykel ykol)'" spell_16 = /substitute -p -- %{PL}%{P0} [@{B}animate weapon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(chik chikky boom!)'" spell_17 = /substitute -p -- %{PL}%{P0} [@{B}anti-magic field@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lorl pu royu veeels)'" spell_18 = /substitute -p -- %{PL}%{P0} [@{B}antivenin@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(And how many, would you say, was in a plethora\\?)'" spell_19 = /substitute -p -- %{PL}%{P0} [@{B}apollo's adagio@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major arx magus)'" spell_20 = /substitute -p -- %{PL}%{P0} [@{B}arcane bulwark@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Lift you up high)'" spell_21 = /substitute -p -- %{PL}%{P0} [@{B}aria of the eagles@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(u lilw fare on veli)'" spell_22 = /substitute -p -- %{PL}%{P0} [@{B}armour of god@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yawa snluvni rouy fo eno elgnis yreve ekat I)'" spell_23 = /substitute -p -- %{PL}%{P0} [@{B}arthorian's revenge@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(DEFLAGRATE!)'" spell_24 = /substitute -p -- %{PL}%{P0} [@{B}ashes to ashes@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn gag gag)'" spell_25 = /substitute -p -- %{PL}%{P0} [@{B}asphyxiation preference@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(norbitz gag gag)'" spell_26 = /substitute -p -- %{PL}%{P0} [@{B}asphyxiation vulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(infomium centa)'" spell_27 = /substitute -p -- %{PL}%{P0} [@{B}aura detection@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ja paivan vari oli\\?)'" spell_28 = /substitute -p -- %{PL}%{P0} [@{B}aura sense@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(rospse lodm nad gufsun)'" spell_29 = /substitute -p -- %{PL}%{P0} [@{B}autumn's breath@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tih eth seonzo tunbot)'" spell_30 = /substitute -p -- %{PL}%{P0} [@{B}awaken talisman@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Aks Bijl Aks)'" spell_31 = /substitute -p -- %{PL}%{P0} [@{B}balance axe@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(In my gypsy eye I see\\.\\.\\. YOU!)'" spell_32 = /substitute -p -- %{PL}%{P0} [@{B}baleful curse@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(juciadious thalgis)'" spell_33 = /substitute -p -- %{PL}%{P0} [@{B}banish undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(whooomp dere itis)'" spell_34 = /substitute -p -- %{PL}%{P0} [@{B}banishment@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(And a tumble in the hay)'" spell_35 = /substitute -p -- %{PL}%{P0} [@{B}bario's bawdy ballad@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(crusta velieris)'" spell_36 = /substitute -p -- %{PL}%{P0} [@{B}barkskin@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(negatus HUH)'" spell_37 = /substitute -p -- %{PL}%{P0} [@{B}barrier of the mind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Acidzzzz Pigeonzzz)'" spell_38 = /substitute -p -- %{PL}%{P0} [@{B}beaks of acid@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Fight, for your right\\.\\.\\.!)'" spell_39 = /substitute -p -- %{PL}%{P0} [@{B}berserker's bravura@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rampiric dracular)'" spell_40 = /substitute -p -- %{PL}%{P0} [@{B}black orb@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nuljia srief)'" spell_41 = /substitute -p -- %{PL}%{P0} [@{B}blade blessing@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(macula valetudo)'" spell_42 = /substitute -p -- %{PL}%{P0} [@{B}blemished health@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(iihana valo)'" spell_43 = /substitute -p -- %{PL}%{P0} [@{B}blindness@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(BurrR froost vycolDd)'" spell_44 = /substitute -p -- %{PL}%{P0} [@{B}blizzard storm@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(cie tylscars)'" spell_45 = /substitute -p -- %{PL}%{P0} [@{B}blizzard@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(intorqueo aeris)'" spell_46 = /substitute -p -- %{PL}%{P0} [@{B}blurred image@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Spiritus releasi manr)'" spell_47 = /substitute -p -- %{PL}%{P0} [@{B}bonded spirits@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(sochani CRACK)'" spell_48 = /substitute -p -- %{PL}%{P0} [@{B}bone shatter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tola pu niarbi)'" spell_49 = /substitute -p -- %{PL}%{P0} [@{B}brain unpain@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(BOOM SHAQATAK!)'" spell_50 = /substitute -p -- %{PL}%{P0} [@{B}brainstorm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(goynex hirc)'" spell_51 = /substitute -p -- %{PL}%{P0} [@{B}breath of life@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yacmer gendosos)'" spell_52 = /substitute -p -- %{PL}%{P0} [@{B}brew cold cream@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo sirtes 0)'" spell_53 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of 0 resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo 0)'" spell_54 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of 0@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo bomlipsotep)'" spell_55 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of charisma@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo nuttisiontoc)'" spell_56 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of constitution@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo yexdirtet)'" spell_57 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of dexterity@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo ligincelteen)'" spell_58 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of intelligence@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo teeearnognir)'" spell_59 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of regeneration@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo niratosreto)'" spell_60 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of restoration@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo mastani)'" spell_61 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of stamina@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo negttrsh)'" spell_62 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of strength@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo rollipwew)'" spell_63 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of willpower@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish rfo dowsim)'" spell_64 = /substitute -p -- %{PL}%{P0} [@{B}brew elixir of wisdom@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes lay'ara)'" spell_65 = /substitute -p -- %{PL}%{P0} [@{B}brew paste of elemental preservation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes 0)'" spell_66 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of 0 resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes cadi)'" spell_67 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of acid resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes yiansphiatox)'" spell_68 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of asphyxiation resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes lodc)'" spell_69 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of cold resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes cectriel)'" spell_70 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of electric resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes refi)'" spell_71 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of fire resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes gilmaca)'" spell_72 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of magical resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes yiphslac)'" spell_73 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of physical resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes sionop)'" spell_74 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of poison resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nirkd tish ot sirtes coispin)'" spell_75 = /substitute -p -- %{PL}%{P0} [@{B}brew salve of psionic resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ripyut si eth yke)'" spell_76 = /substitute -p -- %{PL}%{P0} [@{B}brew sweetwater@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Uckte Solarus)'" spell_77 = /substitute -p -- %{PL}%{P0} [@{B}bright light@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(So then the mage's elixir took effect)'" spell_78 = /substitute -p -- %{PL}%{P0} [@{B}cabalist's saga@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Deemo argoth)'" spell_79 = /substitute -p -- %{PL}%{P0} [@{B}call demonic armour@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(brazzzzazwwaak)'" spell_80 = /substitute -p -- %{PL}%{P0} [@{B}call flock@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Xeratox daimio sword)'" spell_81 = /substitute -p -- %{PL}%{P0} [@{B}call for sword@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Xeratox daimyo sword)'" spell_82 = /substitute -p -- %{PL}%{P0} [@{B}call for sword@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Asgalh dareth)'" spell_83 = /substitute -p -- %{PL}%{P0} [@{B}call grimoire@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(URIKA!!)'" spell_84 = /substitute -p -- %{PL}%{P0} [@{B}call lightning@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tere tulemast dareth)'" spell_85 = /substitute -p -- %{PL}%{P0} [@{B}call mind control device@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Spiridam roes spiridam roes)'" spell_86 = /substitute -p -- %{PL}%{P0} [@{B}call spirit@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lomat veks)'" spell_87 = /substitute -p -- %{PL}%{P0} [@{B}cancel holiday@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(I call upon the darkness of mine soul)'" spell_88 = /substitute -p -- %{PL}%{P0} [@{B}cantana of shadow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pur purrrrr purrrrrrr)'" spell_89 = /substitute -p -- %{PL}%{P0} [@{B}cat eyes@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(judicandus qweuiyafkjh sfdhg)'" spell_90 = /substitute -p -- %{PL}%{P0} [@{B}cause critical wounds@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Ur laif saxs an it das it veery baadly)'" spell_91 = /substitute -p -- %{PL}%{P0} [@{B}cause despair@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Flunssa rox\\.\\. NOOT!)'" spell_92 = /substitute -p -- %{PL}%{P0} [@{B}cause disease@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(judicandus pikkuparannus)'" spell_93 = /substitute -p -- %{PL}%{P0} [@{B}cause light wounds@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(judicandus kohtuullista)'" spell_94 = /substitute -p -- %{PL}%{P0} [@{B}cause serious wounds@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor subsisto solvo)'" spell_95 = /substitute -p -- %{PL}%{P0} [@{B}caustic opposition@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(quidaes lauruvitum cruoris divinae)'" spell_96 = /substitute -p -- %{PL}%{P0} [@{B}celestial disposition@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Zechan mool gnaur)'" spell_97 = /substitute -p -- %{PL}%{P0} [@{B}chain@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(solis daenaelus)'" spell_98 = /substitute -p -- %{PL}%{P0} [@{B}channel life@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Death death death\\.\\.\\.aragaraum death esheer)'" spell_99 = /substitute -p -- %{PL}%{P0} [@{B}chant of death@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(You miserable bags of bones!  Sally Forth!)'" spell_100 = /substitute -p -- %{PL}%{P0} [@{B}chant of fortitude@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(The devil inside, The devil inside\\.\\.\\.)'" spell_101 = /substitute -p -- %{PL}%{P0} [@{B}chant of the beast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Gzreath Czruxh)'" spell_102 = /substitute -p -- %{PL}%{P0} [@{B}chaos bane@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(SUMANI BUUM)'" spell_103 = /substitute -p -- %{PL}%{P0} [@{B}chaos bolt@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kaei aradus siirwe)'" spell_104 = /substitute -p -- %{PL}%{P0} [@{B}chaos cube@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Ultimatum chaosium orbeee)'" spell_105 = /substitute -p -- %{PL}%{P0} [@{B}chaos immolation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kheiooszoun)'" spell_106 = /substitute -p -- %{PL}%{P0} [@{B}chaos magic zone@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Illus wallis)'" spell_107 = /substitute -p -- %{PL}%{P0} [@{B}chaos wall@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(brawwk brawwk join me!)'" spell_108 = /substitute -p -- %{PL}%{P0} [@{B}charm pigeon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Undeadis meerk follo)'" spell_109 = /substitute -p -- %{PL}%{P0} [@{B}charm undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(brwwwaaaaaak brrrrrrwaaaaaaak)'" spell_110 = /substitute -p -- %{PL}%{P0} [@{B}chicken spray@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Dhzethandz)'" spell_111 = /substitute -p -- %{PL}%{P0} [@{B}chill touch@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(selrow louclarem tinomo)'" spell_112 = /substitute -p -- %{PL}%{P0} [@{B}chill weapon@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(meht ekohc)'" spell_113 = /substitute -p -- %{PL}%{P0} [@{B}choke@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Afterall, you don't want a flea collar, do you\\?)'" spell_114 = /substitute -p -- %{PL}%{P0} [@{B}chorus of serenity@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dras dark circulos)'" spell_115 = /substitute -p -- %{PL}%{P0} [@{B}circle of darkness@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tehad si tno teh den)'" spell_116 = /substitute -p -- %{PL}%{P0} [@{B}circle of life@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Circulos aras protecto)'" spell_117 = /substitute -p -- %{PL}%{P0} [@{B}circle of protection@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ala tule paha kakku tule hyva)'" spell_118 = /substitute -p -- %{PL}%{P0} [@{B}clairvoyance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Who is the greatest sorcerer in the land\\?)'" spell_119 = /substitute -p -- %{PL}%{P0} [@{B}claris' melody of mana@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Efil fo ied)'" spell_120 = /substitute -p -- %{PL}%{P0} [@{B}cleansing harmony@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(alecto kalifan)'" spell_121 = /substitute -p -- %{PL}%{P0} [@{B}clinging darkness@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(Ffulf fo lluf)'" spell_122 = /substitute -p -- %{PL}%{P0} [@{B}cloud kill@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tge em na lurbelam)'" spell_123 = /substitute -p -- %{PL}%{P0} [@{B}cloudburst@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihinwolc)'" spell_124 = /substitute -p -- %{PL}%{P0} [@{B}clown heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn freez merc)'" spell_125 = /substitute -p -- %{PL}%{P0} [@{B}cold preference@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(rexx frez)'" spell_126 = /substitute -p -- %{PL}%{P0} [@{B}cold ray@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(norbitz antifreez merc)'" spell_127 = /substitute -p -- %{PL}%{P0} [@{B}cold vulnerability@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(ahction Kamera lIGhts)'" spell_128 = /substitute -p -- %{PL}%{P0} [@{B}colored lights@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(inionican revibalana colour)'" spell_129 = /substitute -p -- %{PL}%{P0} [@{B}colourful berry@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(raiale yursev pmas)'" spell_130 = /substitute -p -- %{PL}%{P0} [@{B}commune with nature@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(inthalas tol maharas)'" spell_131 = /substitute -p -- %{PL}%{P0} [@{B}conflagration@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tellam ym teg em tel)'" spell_132 = /substitute -p -- %{PL}%{P0} [@{B}confuse@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Confuzess skerg)'" spell_133 = /substitute -p -- %{PL}%{P0} [@{B}confusion@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lito lito lobi dan lubebb)'" spell_134 = /substitute -p -- %{PL}%{P0} [@{B}conjure cauldron@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(aym u tounniam alfl nupo oyu)'" spell_135 = /substitute -p -- %{PL}%{P0} [@{B}conjure earth elemental@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ruyeo yagnilp tihw ifre)'" spell_136 = /substitute -p -- %{PL}%{P0} [@{B}conjure fire elemental@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(varies with elemental type)'" spell_137 = /substitute -p -- %{PL}%{P0} [@{B}conjure lesser elemental@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ari ticindgnonio nad rectlan thae)'" spell_138 = /substitute -p -- %{PL}%{P0} [@{B}control temperature@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(urak)'" spell_139 = /substitute -p -- %{PL}%{P0} [@{B}control@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(bustsittue eraa glahien)'" spell_140 = /substitute -p -- %{PL}%{P0} [@{B}corporeal song of healing@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major subsisto concremo)'" spell_141 = /substitute -p -- %{PL}%{P0} [@{B}corrosive opposition@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(Hzzzt shhhh ocrrode)'" spell_142 = /substitute -p -- %{PL}%{P0} [@{B}corrosive wind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(soul ez appqzar)'" spell_143 = /substitute -p -- %{PL}%{P0} [@{B}corrupt soul@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(wroth'niq GZZ)'" spell_144 = /substitute -p -- %{PL}%{P0} [@{B}corrupted barrier@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Hahahacacklesnickermuahneener)'" spell_145 = /substitute -p -- %{PL}%{P0} [@{B}crash all in mud@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Il'a goaer mahdos)'" spell_146 = /substitute -p -- %{PL}%{P0} [@{B}create clone@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yum yum)'" spell_147 = /substitute -p -- %{PL}%{P0} [@{B}create food@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(selur mip)'" spell_148 = /substitute -p -- %{PL}%{P0} [@{B}create healing potion@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(kroises pennonen rulettaa)'" spell_149 = /substitute -p -- %{PL}%{P0} [@{B}create money@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(tarenu sedton vigefor)'" spell_150 = /substitute -p -- %{PL}%{P0} [@{B}creeping doom@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz pfzikue)'" spell_151 = /substitute -p -- %{PL}%{P0} [@{B}crumbling feet@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa sirourcihiili)'" spell_152 = /substitute -p -- %{PL}%{P0} [@{B}cruoris wizheal@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(moleculos friitzos)'" spell_153 = /substitute -p -- %{PL}%{P0} [@{B}cryokinesis@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ees nac uoy)'" spell_154 = /substitute -p -- %{PL}%{P0} [@{B}cure blindness@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa qweaizkah)'" spell_155 = /substitute -p -- %{PL}%{P0} [@{B}cure critical wounds@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Demonix regenerum)'" spell_156 = /substitute -p -- %{PL}%{P0} [@{B}cure demon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(retteb leef uoy)'" spell_157 = /substitute -p -- %{PL}%{P0} [@{B}cure disease@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa pikkuparannus)'" spell_158 = /substitute -p -- %{PL}%{P0} [@{B}cure light wounds@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa kohtuullista)'" spell_159 = /substitute -p -- %{PL}%{P0} [@{B}cure serious wounds@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Fnead undah)'" spell_160 = /substitute -p -- %{PL}%{P0} [@{B}cure undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Bork Bork Bork)'" spell_161 = /substitute -p -- %{PL}%{P0} [@{B}curse of the chef@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(\\|\\)u\\|\\)3, y0u r0\\(\\|<0rZ!)'" spell_162 = /substitute -p -- %{PL}%{P0} [@{B}curse of the leet@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(In this one the force is strong)'" spell_163 = /substitute -p -- %{PL}%{P0} [@{B}curse of the master@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Meat Me At Thinker)'" spell_164 = /substitute -p -- %{PL}%{P0} [@{B}curse of the moron@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(suojaxit paal paa)'" spell_165 = /substitute -p -- %{PL}%{P0} [@{B}curse shield@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Evilth dah triumpht)'" spell_166 = /substitute -p -- %{PL}%{P0} [@{B}dark absolution@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Argames wharas st'rak)'" spell_167 = /substitute -p -- %{PL}%{P0} [@{B}dark embryo@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(MUAHAHAAHAH)'" spell_168 = /substitute -p -- %{PL}%{P0} [@{B}dark force@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Arak rakma lleps wohwonk)'" spell_169 = /substitute -p -- %{PL}%{P0} [@{B}dark teach@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Asgarth fakur burnth)'" spell_170 = /substitute -p -- %{PL}%{P0} [@{B}darkfire@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ne lux)'" spell_171 = /substitute -p -- %{PL}%{P0} [@{B}darkness@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Oal g'Alno!)'" spell_172 = /substitute -p -- %{PL}%{P0} [@{B}deadly attention@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(damaa bounchiii)'" spell_173 = /substitute -p -- %{PL}%{P0} [@{B}death armour@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(fwlat phsulfur ackid)'" spell_174 = /substitute -p -- %{PL}%{P0} [@{B}death fog@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Death sanctorium regeneratum)'" spell_175 = /substitute -p -- %{PL}%{P0} [@{B}death sanctification@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(Morf cum acid noxam!)'" spell_176 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(Morf cum asphyxiation noxam!)'" spell_177 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Morf cum cold noxam!)'" spell_178 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Morf cum fire noxam!)'" spell_179 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Morf cum magical noxam!)'" spell_180 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Morf cum physical noxam!)'" spell_181 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(Morf cum poison noxam!)'" spell_182 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Morf cum you should not see this noxam!)'" spell_183 = /substitute -p -- %{PL}%{P0} [@{B}death wish@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Deeeaathhh deathhhh)'" spell_184 = /substitute -p -- %{PL}%{P0} [@{B}death@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(shish boom bah)'" spell_185 = /substitute -p -- %{PL}%{P0} [@{B}deathslash@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(mi ton guknics ti tou)'" spell_186 = /substitute -p -- %{PL}%{P0} [@{B}degrade venom@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(depris spiritvum)'" spell_187 = /substitute -p -- %{PL}%{P0} [@{B}deliverance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(demonicus physique)'" spell_188 = /substitute -p -- %{PL}%{P0} [@{B}demonic blood@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Thoooonthaaar)'" spell_189 = /substitute -p -- %{PL}%{P0} [@{B}demonic energy@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(demonicus spiritus)'" spell_190 = /substitute -p -- %{PL}%{P0} [@{B}demonic rage@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Hurpuz anzz slazzh)'" spell_191 = /substitute -p -- %{PL}%{P0} [@{B}demonic shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(demonicus celeritas)'" spell_192 = /substitute -p -- %{PL}%{P0} [@{B}demonic speed@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kooraxema Evil drojgihwe'yl)'" spell_193 = /substitute -p -- %{PL}%{P0} [@{B}demonic test@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(aufero fervens)'" spell_194 = /substitute -p -- %{PL}%{P0} [@{B}deprive warmth@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Dharg dhestruxt)'" spell_195 = /substitute -p -- %{PL}%{P0} [@{B}destruction@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(kuks kuspaah)'" spell_196 = /substitute -p -- %{PL}%{P0} [@{B}detect alignment@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Hazteedhz)'" spell_197 = /substitute -p -- %{PL}%{P0} [@{B}devastating hate@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz dxetrkue)'" spell_198 = /substitute -p -- %{PL}%{P0} [@{B}devilish tickle@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(KNOCK KNOCK)'" spell_199 = /substitute -p -- %{PL}%{P0} [@{B}dimension door@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(SUMUA)'" spell_200 = /substitute -p -- %{PL}%{P0} [@{B}dimensional gate@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(gelu cutis)'" spell_201 = /substitute -p -- %{PL}%{P0} [@{B}diminish defence@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(To die\\.  Alone\\.  In the rain\\.)'" spell_202 = /substitute -p -- %{PL}%{P0} [@{B}dirge of despair@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Eagon!)'" spell_203 = /substitute -p -- %{PL}%{P0} [@{B}dismiss@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(shiee corpore neehs)'" spell_204 = /substitute -p -- %{PL}%{P0} [@{B}dispel enchantment@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(loxium boxium boom)'" spell_205 = /substitute -p -- %{PL}%{P0} [@{B}dispel evil@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(dhuax goodisx)'" spell_206 = /substitute -p -- %{PL}%{P0} [@{B}dispel good@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(UUJ tnUoD' an'wa bii KoeOEr'seeD)'" spell_207 = /substitute -p -- %{PL}%{P0} [@{B}dispel greater curse@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(fizzzmo h2o NOOOT)'" spell_208 = /substitute -p -- %{PL}%{P0} [@{B}dispel mist@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(juciadious miduis)'" spell_209 = /substitute -p -- %{PL}%{P0} [@{B}dispel undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(sumuj puusilmils)'" spell_210 = /substitute -p -- %{PL}%{P0} [@{B}displacement@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(zan fah acid zing)'" spell_211 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(zan fah asphyxiation zing)'" spell_212 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(zan fah cold zing)'" spell_213 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(zan fah fire zing)'" spell_214 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(zan fah magical zing)'" spell_215 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(zan fah physical zing)'" spell_216 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(zan fah poison zing)'" spell_217 = /substitute -p -- %{PL}%{P0} [@{B}disruption@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Joor feet ar nou longr stuk to da graund)'" spell_218 = /substitute -p -- %{PL}%{P0} [@{B}dissolve@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Nyt loppu lautasten heittely ja riitojen peittely!)'" spell_219 = /substitute -p -- %{PL}%{P0} [@{B}divorce@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Roarrrrrrrin RRRRRRROASTIM)'" spell_220 = /substitute -p -- %{PL}%{P0} [@{B}dragon breath@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(gansord cna ese githvneery)'" spell_221 = /substitute -p -- %{PL}%{P0} [@{B}dragon sight@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(TAP the waters to drain away their resolve and hate!)'" spell_222 = /substitute -p -- %{PL}%{P0} [@{B}drain power@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Driel amuras drakka)'" spell_223 = /substitute -p -- %{PL}%{P0} [@{B}draining mine@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Bharas grand bleeed)'" spell_224 = /substitute -p -- %{PL}%{P0} [@{B}draw blood@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(Rockim sockim acidooush)'" spell_225 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(Rockim sockim asphyxiationooush)'" spell_226 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Rockim sockim coldooush)'" spell_227 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(Rockim sockim fireooush)'" spell_228 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Rockim sockim magicalooush)'" spell_229 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Rockim sockim physicalooush)'" spell_230 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(Rockim sockim poisonooush)'" spell_231 = /substitute -p -- %{PL}%{P0} [@{B}earthquake@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(ex morituri)'" spell_232 = /substitute -p -- %{PL}%{P0} [@{B}effusion of entity@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio shiirza electric)'" spell_233 = /substitute -p -- %{PL}%{P0} [@{B}electric blade@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(norbitz AC/DC)'" spell_234 = /substitute -p -- %{PL}%{P0} [@{B}electric vulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rignef ni thilg kestoc)'" spell_235 = /substitute -p -- %{PL}%{P0} [@{B}electrical field@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(Elur ynoga fo efiL)'" spell_236 = /substitute -p -- %{PL}%{P0} [@{B}electro-crush@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(nequam victus confundo mentis)'" spell_237 = /substitute -p -- %{PL}%{P0} [@{B}elemental disarray@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(azatharr dakanarr daidonur)'" spell_238 = /substitute -p -- %{PL}%{P0} [@{B}enchant arrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(corpore odimeugh)'" spell_239 = /substitute -p -- %{PL}%{P0} [@{B}enchant corpse@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Qwitem mazicous emfeb phiturez)'" spell_240 = /substitute -p -- %{PL}%{P0} [@{B}enchant item@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kalranos Thulos)'" spell_241 = /substitute -p -- %{PL}%{P0} [@{B}enchant weapon@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(tsalb meht)'" spell_242 = /substitute -p -- %{PL}%{P0} [@{B}enchanted blast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(obfirmo munimentum)'" spell_243 = /substitute -p -- %{PL}%{P0} [@{B}encrypt shielding@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor auxilium pneum)'" spell_244 = /substitute -p -- %{PL}%{P0} [@{B}endure void@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(fulmen infractus)'" spell_245 = /substitute -p -- %{PL}%{P0} [@{B}energetic frailty@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(suck suuuuuuck suuuuuuuuuuuuuuuuuuuuck)'" spell_246 = /substitute -p -- %{PL}%{P0} [@{B}energy drain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(candidus lorica)'" spell_247 = /substitute -p -- %{PL}%{P0} [@{B}energy hauberk@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(amplio sensus)'" spell_248 = /substitute -p -- %{PL}%{P0} [@{B}enhance senses@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Spiridam nelar)'" spell_249 = /substitute -p -- %{PL}%{P0} [@{B}enlarge spirit@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(laixu duqiz tonka)'" spell_250 = /substitute -p -- %{PL}%{P0} [@{B}enlarge weapon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(FOLAXI POSITRO)'" spell_251 = /substitute -p -- %{PL}%{P0} [@{B}enlightenment@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Undeadis controlla)'" spell_252 = /substitute -p -- %{PL}%{P0} [@{B}enslavement@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(kacj asw v colo ikd)'" spell_253 = /substitute -p -- %{PL}%{P0} [@{B}entangle@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Pix)'" spell_254 = /substitute -p -- %{PL}%{P0} [@{B}estimate weight@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(paljonko maksaa kilo hanhen maksaa)'" spell_255 = /substitute -p -- %{PL}%{P0} [@{B}estimate worth@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(WARP SPEED)'" spell_256 = /substitute -p -- %{PL}%{P0} [@{B}ethereal gate@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rewop evah siht soed)'" spell_257 = /substitute -p -- %{PL}%{P0} [@{B}evaluate magical power@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(TAP the plains to bring retribution to mine enemies)'" spell_258 = /substitute -p -- %{PL}%{P0} [@{B}eye for an eye@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Seeeeeeeeee thiiiiiiiiiiings)'" spell_259 = /substitute -p -- %{PL}%{P0} [@{B}eye of otus@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(anatar magadu tais)'" spell_260 = /substitute -p -- %{PL}%{P0} [@{B}eyes of the marksman@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(gerit riteg gubrinn githrb)'" spell_261 = /substitute -p -- %{PL}%{P0} [@{B}eyes of the tiger@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(flur`dso osne)'" spell_262 = /substitute -p -- %{PL}%{P0} [@{B}faerie fire@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tseh tseh kiss kiss)'" spell_263 = /substitute -p -- %{PL}%{P0} [@{B}familiar@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Wheeeooohoooeeewl!)'" spell_264 = /substitute -p -- %{PL}%{P0} [@{B}fear@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Wheeeooohoooeeewl)'" spell_265 = /substitute -p -- %{PL}%{P0} [@{B}fear@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Feast, Feast for the Lord)'" spell_266 = /substitute -p -- %{PL}%{P0} [@{B}feast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hoyhen)'" spell_267 = /substitute -p -- %{PL}%{P0} [@{B}feather weight@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(gish gosh)'" spell_268 = /substitute -p -- %{PL}%{P0} [@{B}feeblemind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Eliendien nu Fenn Ram-enna)'" spell_269 = /substitute -p -- %{PL}%{P0} [@{B}fenn ram@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(kuole)'" spell_270 = /substitute -p -- %{PL}%{P0} [@{B}finger of death@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(mortis)'" spell_271 = /substitute -p -- %{PL}%{P0} [@{B}finger of death@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio thorex fire)'" spell_272 = /substitute -p -- %{PL}%{P0} [@{B}fire blade@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(malosi tashana)'" spell_273 = /substitute -p -- %{PL}%{P0} [@{B}fire blast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Watch the torch\\.\\.\\.)'" spell_274 = /substitute -p -- %{PL}%{P0} [@{B}fire breathing act@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn burn unres)'" spell_275 = /substitute -p -- %{PL}%{P0} [@{B}fire preference@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lupl npi nad hwrot)'" spell_276 = /substitute -p -- %{PL}%{P0} [@{B}fire seeds@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(norbitz burn unres)'" spell_277 = /substitute -p -- %{PL}%{P0} [@{B}fire vulnerability@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(hto freaer)'" spell_278 = /substitute -p -- %{PL}%{P0} [@{B}fireball@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(khar tra erfi)'" spell_279 = /substitute -p -- %{PL}%{P0} [@{B}firebolt@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dhazzzziii firezzz dhemicus)'" spell_280 = /substitute -p -- %{PL}%{P0} [@{B}fireclaws@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(nrub ot hessa)'" spell_281 = /substitute -p -- %{PL}%{P0} [@{B}fist of ra@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(shal dra frie)'" spell_282 = /substitute -p -- %{PL}%{P0} [@{B}flame arrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(zorar rhasp dan rugnibn tho)'" spell_283 = /substitute -p -- %{PL}%{P0} [@{B}flame blade@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(judicandus ZAP POOF)'" spell_284 = /substitute -p -- %{PL}%{P0} [@{B}flamestrike@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(rife orf het esmsas)'" spell_285 = /substitute -p -- %{PL}%{P0} [@{B}flaming pestilence@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Magica fulminatus!)'" spell_286 = /substitute -p -- %{PL}%{P0} [@{B}flash of power@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Plaguras zaram death shakaram)'" spell_287 = /substitute -p -- %{PL}%{P0} [@{B}flesh rot@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(muudubba zzztouunnddiiiks)'" spell_288 = /substitute -p -- %{PL}%{P0} [@{B}flesh to stone@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(It's going to be raining men, hallelujah)'" spell_289 = /substitute -p -- %{PL}%{P0} [@{B}flight@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ccarr reks)'" spell_290 = /substitute -p -- %{PL}%{P0} [@{B}floating disc@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hooked on phonics)'" spell_291 = /substitute -p -- %{PL}%{P0} [@{B}floating letters@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pimp pimp PIMP)'" spell_292 = /substitute -p -- %{PL}%{P0} [@{B}force shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(HUH\\?\\?)'" spell_293 = /substitute -p -- %{PL}%{P0} [@{B}forget@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(afflictus corpus)'" spell_294 = /substitute -p -- %{PL}%{P0} [@{B}fragile frame@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Raaag eagon)'" spell_295 = /substitute -p -- %{PL}%{P0} [@{B}free servant@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(tulipa kylyma)'" spell_296 = /substitute -p -- %{PL}%{P0} [@{B}freezing wind@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(fraz frizz)'" spell_297 = /substitute -p -- %{PL}%{P0} [@{B}frost arrow@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(hawtc ruyo teps)'" spell_298 = /substitute -p -- %{PL}%{P0} [@{B}gaia's vengeance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(faaaaaaaaarrrrrttttttt)'" spell_299 = /substitute -p -- %{PL}%{P0} [@{B}gaseous form@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio ghooor moooooor)'" spell_300 = /substitute -p -- %{PL}%{P0} [@{B}ghorux blade@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(soooooooooo strong)'" spell_301 = /substitute -p -- %{PL}%{P0} [@{B}giant strength@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(I pledge myself to darkness\\.\\.\\. GIGA SLAVE!)'" spell_302 = /substitute -p -- %{PL}%{P0} [@{B}giga slave@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(Gkhrak Sum Sebolg)'" spell_303 = /substitute -p -- %{PL}%{P0} [@{B}globes of death@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Joor feet ar stuk to da graund)'" spell_304 = /substitute -p -- %{PL}%{P0} [@{B}glue@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(rexx plukk)'" spell_305 = /substitute -p -- %{PL}%{P0} [@{B}golden arrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(inionican revibalana)'" spell_306 = /substitute -p -- %{PL}%{P0} [@{B}good berry@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Hcnets u'h horr)'" spell_307 = /substitute -p -- %{PL}%{P0} [@{B}grave stench@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(klizu burnn arse)'" spell_308 = /substitute -p -- %{PL}%{P0} [@{B}greater acid invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major gag gag)'" spell_309 = /substitute -p -- %{PL}%{P0} [@{B}greater asphyxiation invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(klizu antifreez merc)'" spell_310 = /substitute -p -- %{PL}%{P0} [@{B}greater cold invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major AC/DC)'" spell_311 = /substitute -p -- %{PL}%{P0} [@{B}greater electric invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Fveer igh el grond)'" spell_312 = /substitute -p -- %{PL}%{P0} [@{B}greater elemental shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major burn res)'" spell_313 = /substitute -p -- %{PL}%{P0} [@{B}greater fire invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(glaaaash fleeeesssh moc)'" spell_314 = /substitute -p -- %{PL}%{P0} [@{B}greater invisibility@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(klizu merlin merc)'" spell_315 = /substitute -p -- %{PL}%{P0} [@{B}greater magical invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Maghias grond)'" spell_316 = /substitute -p -- %{PL}%{P0} [@{B}greater magical shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major healaappa)'" spell_317 = /substitute -p -- %{PL}%{P0} [@{B}greater party heal@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(smacking duck)'" spell_318 = /substitute -p -- %{PL}%{P0} [@{B}greater phantom summoning@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(resistin lotsa phys)'" spell_319 = /substitute -p -- %{PL}%{P0} [@{B}greater physical invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(klizu snake biit)'" spell_320 = /substitute -p -- %{PL}%{P0} [@{B}greater poison invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major brain shield)'" spell_321 = /substitute -p -- %{PL}%{P0} [@{B}greater psionic invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok aurahalis)'" spell_322 = /substitute -p -- %{PL}%{P0} [@{B}guise of the angel@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok numiha)'" spell_323 = /substitute -p -- %{PL}%{P0} [@{B}guise of the flayer@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok minarus)'" spell_324 = /substitute -p -- %{PL}%{P0} [@{B}guise of the halfling@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok thorin)'" spell_325 = /substitute -p -- %{PL}%{P0} [@{B}guise of the ogre@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok auralin)'" spell_326 = /substitute -p -- %{PL}%{P0} [@{B}guise of the paladin@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok boraelis)'" spell_327 = /substitute -p -- %{PL}%{P0} [@{B}guise of the skeleton@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(htaln julinstok nyalis)'" spell_328 = /substitute -p -- %{PL}%{P0} [@{B}guise of the titan@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pzar paf)'" spell_329 = /substitute -p -- %{PL}%{P0} [@{B}half heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ti yirnactel sloko kile u tere)'" spell_330 = /substitute -p -- %{PL}%{P0} [@{B}hallucinatory forest@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(teh tengel ethiw tahed)'" spell_331 = /substitute -p -- %{PL}%{P0} [@{B}hand of winter@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(PAF PAF PAF!)'" spell_332 = /substitute -p -- %{PL}%{P0} [@{B}harm body@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(PAF)'" spell_333 = /substitute -p -- %{PL}%{P0} [@{B}harm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hcout t'nac)'" spell_334 = /substitute -p -- %{PL}%{P0} [@{B}harmonious barrier@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hcout tnod)'" spell_335 = /substitute -p -- %{PL}%{P0} [@{B}harmony armour@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(won lluf ruoy knihti)'" spell_336 = /substitute -p -- %{PL}%{P0} [@{B}harmony hand@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Daaa defeaat av EWIL LAGG!)'" spell_337 = /substitute -p -- %{PL}%{P0} [@{B}haste@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(BuuUuUu de ruumeee!!!)'" spell_338 = /substitute -p -- %{PL}%{P0} [@{B}haunt@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(owie betdathurt)'" spell_339 = /substitute -p -- %{PL}%{P0} [@{B}headache@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(haleloojah)'" spell_340 = /substitute -p -- %{PL}%{P0} [@{B}heal all@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(HUOH HUOH HUOH)'" spell_341 = /substitute -p -- %{PL}%{P0} [@{B}heal body@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pzar)'" spell_342 = /substitute -p -- %{PL}%{P0} [@{B}heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(dnuora rehtag)'" spell_343 = /substitute -p -- %{PL}%{P0} [@{B}healing ceremony@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tbah rhilwoolp)'" spell_344 = /substitute -p -- %{PL}%{P0} [@{B}healing draught@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pleh dluohs siht)'" spell_345 = /substitute -p -- %{PL}%{P0} [@{B}healing smoke@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Woooooosshhhh)'" spell_346 = /substitute -p -- %{PL}%{P0} [@{B}healing wind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(stafre louclarem tinomo)'" spell_347 = /substitute -p -- %{PL}%{P0} [@{B}heat weapon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(axk kazo rexla)'" spell_348 = /substitute -p -- %{PL}%{P0} [@{B}heavy weight@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(SAATANA)'" spell_349 = /substitute -p -- %{PL}%{P0} [@{B}hellfire@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Reikaa seinaan)'" spell_350 = /substitute -p -- %{PL}%{P0} [@{B}hole@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(liwl phal muiks equx jox eiks poiz meniks)'" spell_351 = /substitute -p -- %{PL}%{P0} [@{B}holy glow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tbah umd)'" spell_352 = /substitute -p -- %{PL}%{P0} [@{B}holy ground@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(juciadious maximus)'" spell_353 = /substitute -p -- %{PL}%{P0} [@{B}holy hand@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Summoh dheitis lessox)'" spell_354 = /substitute -p -- %{PL}%{P0} [@{B}holy presence@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Xhsashaz wixdoz)'" spell_355 = /substitute -p -- %{PL}%{P0} [@{B}holy wisdom@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ZHOOOOooooooooooiiiii)'" spell_356 = /substitute -p -- %{PL}%{P0} [@{B}howl from beyond@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(TAP the forests to blow away my enemies with wind!)'" spell_357 = /substitute -p -- %{PL}%{P0} [@{B}hurricane@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(leeeewwwwk iiiintoo miii eeeeeeeeeeyezzzz)'" spell_358 = /substitute -p -- %{PL}%{P0} [@{B}hypnotic gaze@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Friozes iazes brr)'" spell_359 = /substitute -p -- %{PL}%{P0} [@{B}ice storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio thorex ice)'" spell_360 = /substitute -p -- %{PL}%{P0} [@{B}iceblade@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Hreht ezeerf)'" spell_361 = /substitute -p -- %{PL}%{P0} [@{B}icebolt@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rex bragh freez)'" spell_362 = /substitute -p -- %{PL}%{P0} [@{B}identify@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Crieite feik obtjeect)'" spell_363 = /substitute -p -- %{PL}%{P0} [@{B}illusion@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(talus aj mahjer)'" spell_364 = /substitute -p -- %{PL}%{P0} [@{B}immolate@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Let our thoughts be as one)'" spell_365 = /substitute -p -- %{PL}%{P0} [@{B}impart knowledge@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Allow me to perform the mind meld)'" spell_366 = /substitute -p -- %{PL}%{P0} [@{B}impart lore@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(REX rex bragh freez)'" spell_367 = /substitute -p -- %{PL}%{P0} [@{B}improved identify@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(ardens amictus)'" spell_368 = /substitute -p -- %{PL}%{P0} [@{B}incendiary coating@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major prohibeo glacie)'" spell_369 = /substitute -p -- %{PL}%{P0} [@{B}infernal vestment@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Ad infinitum)'" spell_370 = /substitute -p -- %{PL}%{P0} [@{B}infinity reincarnation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(demoniki demonnick)'" spell_371 = /substitute -p -- %{PL}%{P0} [@{B}infravision@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Concentrate numbskull)'" spell_372 = /substitute -p -- %{PL}%{P0} [@{B}inner power@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(Beeezzzsss)'" spell_373 = /substitute -p -- %{PL}%{P0} [@{B}insect plaque@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(taprioxein atde)'" spell_374 = /substitute -p -- %{PL}%{P0} [@{B}invigorate@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(validus ferocia)'" spell_375 = /substitute -p -- %{PL}%{P0} [@{B}iron will@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio ghooor moooooor goooood)'" spell_376 = /substitute -p -- %{PL}%{P0} [@{B}jigoku blade@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(ostunna ostunna)'" spell_377 = /substitute -p -- %{PL}%{P0} [@{B}jolts@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(smells like teen spirit)'" spell_378 = /substitute -p -- %{PL}%{P0} [@{B}killing cloud@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ess pee eff yifft)'" spell_379 = /substitute -p -- %{PL}%{P0} [@{B}kiss of helios@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(raera yuouy nadna)'" spell_380 = /substitute -p -- %{PL}%{P0} [@{B}know your audience@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(riiiiiiiiibit ribiiiiiiiit)'" spell_381 = /substitute -p -- %{PL}%{P0} [@{B}kurse@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(infirmus respiro)'" spell_382 = /substitute -p -- %{PL}%{P0} [@{B}labored breathing@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(ignavus animus)'" spell_383 = /substitute -p -- %{PL}%{P0} [@{B}languished soul@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(helvetin hornaan)'" spell_384 = /substitute -p -- %{PL}%{P0} [@{B}lava storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Whiiiiine\\.  Whhhyyyy meeeeeeeee\\?)'" spell_385 = /substitute -p -- %{PL}%{P0} [@{B}leomund's lament@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lexa burnn arse)'" spell_386 = /substitute -p -- %{PL}%{P0} [@{B}lesser acid invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor gag gag)'" spell_387 = /substitute -p -- %{PL}%{P0} [@{B}lesser asphyxiation invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lexa antifreez merc)'" spell_388 = /substitute -p -- %{PL}%{P0} [@{B}lesser cold invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor AC/DC)'" spell_389 = /substitute -p -- %{PL}%{P0} [@{B}lesser electric invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Fveer igh el lheond)'" spell_390 = /substitute -p -- %{PL}%{P0} [@{B}lesser elemental shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor hot hot)'" spell_391 = /substitute -p -- %{PL}%{P0} [@{B}lesser fire invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lexa merlin merc)'" spell_392 = /substitute -p -- %{PL}%{P0} [@{B}lesser magical invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Maghias lheond)'" spell_393 = /substitute -p -- %{PL}%{P0} [@{B}lesser magical shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor healaappa)'" spell_394 = /substitute -p -- %{PL}%{P0} [@{B}lesser party heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(resistin phys)'" spell_395 = /substitute -p -- %{PL}%{P0} [@{B}lesser physical invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lexa snake biit)'" spell_396 = /substitute -p -- %{PL}%{P0} [@{B}lesser poison invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor brain shield)'" spell_397 = /substitute -p -- %{PL}%{P0} [@{B}lesser psionic invulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Imaan toraleev)'" spell_398 = /substitute -p -- %{PL}%{P0} [@{B}levitation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(shesa ot shesa\\.\\.\\.tusd ot tusd)'" spell_399 = /substitute -p -- %{PL}%{P0} [@{B}life beyond death@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(iiiz threaaa enziiibzii yt tzhreee\\?)'" spell_400 = /substitute -p -- %{PL}%{P0} [@{B}life detection@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(evaw to rouy htlaeh)'" spell_401 = /substitute -p -- %{PL}%{P0} [@{B}life leech@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lux)'" spell_402 = /substitute -p -- %{PL}%{P0} [@{B}light@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(shckh eltrc)'" spell_403 = /substitute -p -- %{PL}%{P0} [@{B}lightning bolt@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major tutamen tempestas)'" spell_404 = /substitute -p -- %{PL}%{P0} [@{B}lightning guard@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Rumbling Storm\\.\\.\\. Come Forth!)'" spell_405 = /substitute -p -- %{PL}%{P0} [@{B}lightning storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio enox hit)'" spell_406 = /substitute -p -- %{PL}%{P0} [@{B}lightsword@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(knig fo teh lejnug)'" spell_407 = /substitute -p -- %{PL}%{P0} [@{B}lion's heart@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yee ysp twih ym tletli yee)'" spell_408 = /substitute -p -- %{PL}%{P0} [@{B}locate animals@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(yypoys takiap)'" spell_409 = /substitute -p -- %{PL}%{P0} [@{B}lower acid resistance@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(uppol amli)'" spell_410 = /substitute -p -- %{PL}%{P0} [@{B}lower asphyxiation resistance@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(nenakkap eehuak)'" spell_411 = /substitute -p -- %{PL}%{P0} [@{B}lower cold resistance@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(naaisarotsip nemros nisnoyt)'" spell_412 = /substitute -p -- %{PL}%{P0} [@{B}lower electric resistance@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(amuuk naarias)'" spell_413 = /substitute -p -- %{PL}%{P0} [@{B}lower fire resistance@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(ahun nenigaam)'" spell_414 = /substitute -p -- %{PL}%{P0} [@{B}lower magical resistance@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(otnuk okkieh hohu)'" spell_415 = /substitute -p -- %{PL}%{P0} [@{B}lower physical resistance@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(aaniiv aakiil)'" spell_416 = /substitute -p -- %{PL}%{P0} [@{B}lower poison resistance@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(aanarub emmig)'" spell_417 = /substitute -p -- %{PL}%{P0} [@{B}lower psionic resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Like unto a wolverine)'" spell_418 = /substitute -p -- %{PL}%{P0} [@{B}lullaby of life@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Let me tell you a tale of my lost love)'" spell_419 = /substitute -p -- %{PL}%{P0} [@{B}lyrics of sorrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Masticanus Mephistophalus)'" spell_420 = /substitute -p -- %{PL}%{P0} [@{B}mabanon's whip@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz mxanaregpx)'" spell_421 = /substitute -p -- %{PL}%{P0} [@{B}mages bane@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(frtizvg)'" spell_422 = /substitute -p -- %{PL}%{P0} [@{B}magic missile@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn merlin merc)'" spell_423 = /substitute -p -- %{PL}%{P0} [@{B}magical preference@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Tu est nunc in fide TEMPUS!)'" spell_424 = /substitute -p -- %{PL}%{P0} [@{B}magical vestment@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(norbitz merlin merc)'" spell_425 = /substitute -p -- %{PL}%{P0} [@{B}magical vulnerability@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Majiik mgeer wdin)'" spell_426 = /substitute -p -- %{PL}%{P0} [@{B}magical wave@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(struh yawa rojami)'" spell_427 = /substitute -p -- %{PL}%{P0} [@{B}major distant heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(struhti yawa raf)'" spell_428 = /substitute -p -- %{PL}%{P0} [@{B}major distant transfer@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Azrahas grand suuuuck suuuuck)'" spell_429 = /substitute -p -- %{PL}%{P0} [@{B}major energy drain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pzar paf foo)'" spell_430 = /substitute -p -- %{PL}%{P0} [@{B}major heal@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Adrin corpus suuuck suuck burp)'" spell_431 = /substitute -p -- %{PL}%{P0} [@{B}major life leech@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(resistin lotsa maagi)'" spell_432 = /substitute -p -- %{PL}%{P0} [@{B}major magical resistance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rojamuoy ootem)'" spell_433 = /substitute -p -- %{PL}%{P0} [@{B}major transfer@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Shrag naer drih)'" spell_434 = /substitute -p -- %{PL}%{P0} [@{B}make scar@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(By all I hold dear, why did you go\\?  WHY\\?)'" spell_435 = /substitute -p -- %{PL}%{P0} [@{B}malach's mourning@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(suuuuck suuck BURP)'" spell_436 = /substitute -p -- %{PL}%{P0} [@{B}mana drain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(I LOVE MAGIC)'" spell_437 = /substitute -p -- %{PL}%{P0} [@{B}mana leech@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(TAP the boundless seas to give ALL their energy to ME!!)'" spell_438 = /substitute -p -- %{PL}%{P0} [@{B}mana short@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dza s'hra evilum)'" spell_439 = /substitute -p -- %{PL}%{P0} [@{B}mark of cain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(darg zarr om ni zomm)'" spell_440 = /substitute -p -- %{PL}%{P0} [@{B}mark of zomm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Mrzk uuands)'" spell_441 = /substitute -p -- %{PL}%{P0} [@{B}mark undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor mentis contego)'" spell_442 = /substitute -p -- %{PL}%{P0} [@{B}mental aegis@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(vaxtextraktdryck)'" spell_443 = /substitute -p -- %{PL}%{P0} [@{B}mental glance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(In your heeead, in your heeeeeeeaad!)'" spell_444 = /substitute -p -- %{PL}%{P0} [@{B}mental illusions@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(WWWZAAAA PSII!!!)'" spell_445 = /substitute -p -- %{PL}%{P0} [@{B}mental storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hiiiiiii hiiii hi)'" spell_446 = /substitute -p -- %{PL}%{P0} [@{B}mental watch@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(blurin blorin)'" spell_447 = /substitute -p -- %{PL}%{P0} [@{B}metamorphosis@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(drazh bragh)'" spell_448 = /substitute -p -- %{PL}%{P0} [@{B}meteor blast@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(drazh illusory bragh)'" spell_449 = /substitute -p -- %{PL}%{P0} [@{B}meteor retort@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(drazh bragh aer)'" spell_450 = /substitute -p -- %{PL}%{P0} [@{B}meteor storm@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(asspurrinn aspperin ASPIRIN)'" spell_451 = /substitute -p -- %{PL}%{P0} [@{B}migraine@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(seapel vige em wepro)'" spell_452 = /substitute -p -- %{PL}%{P0} [@{B}millennium charge@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(psssiiiiis wanna beeaaaloonne toooo)'" spell_453 = /substitute -p -- %{PL}%{P0} [@{B}mind barrier@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(WORDISBOND)'" spell_454 = /substitute -p -- %{PL}%{P0} [@{B}mind control@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tink tank boom)'" spell_455 = /substitute -p -- %{PL}%{P0} [@{B}mind development@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(CARRIER DETECTED)'" spell_456 = /substitute -p -- %{PL}%{P0} [@{B}mind link@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(ala kazam bam)'" spell_457 = /substitute -p -- %{PL}%{P0} [@{B}mind melt@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(brainium crainium)'" spell_458 = /substitute -p -- %{PL}%{P0} [@{B}mind store@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(Knarf appaz ZAP!)'" spell_459 = /substitute -p -- %{PL}%{P0} [@{B}mind tempest@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(SHORYUKEN)'" spell_460 = /substitute -p -- %{PL}%{P0} [@{B}mindfist@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(struh yawa ronimi)'" spell_461 = /substitute -p -- %{PL}%{P0} [@{B}minor distant heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(sdnuow yawa raf)'" spell_462 = /substitute -p -- %{PL}%{P0} [@{B}minor distant transfer@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pu animatsi)'" spell_463 = /substitute -p -- %{PL}%{P0} [@{B}minor unpain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ken on maassa kaunehin)'" spell_464 = /substitute -p -- %{PL}%{P0} [@{B}mirror image@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(AROT arot arot)'" spell_465 = /substitute -p -- %{PL}%{P0} [@{B}mirror mind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(frtizvg STORM)'" spell_466 = /substitute -p -- %{PL}%{P0} [@{B}missile storm@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(fizzzmo h2o)'" spell_467 = /substitute -p -- %{PL}%{P0} [@{B}mist haze@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz xwiszdonx)'" spell_468 = /substitute -p -- %{PL}%{P0} [@{B}moaning laughter@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(moleculos warmos)'" spell_469 = /substitute -p -- %{PL}%{P0} [@{B}molecular agitation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$\\$)'" spell_470 = /substitute -p -- %{PL}%{P0} [@{B}money is power@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ceon ni u lueb nomo)'" spell_471 = /substitute -p -- %{PL}%{P0} [@{B}moonbeam@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nivom ken on maassa kaunehin)'" spell_472 = /substitute -p -- %{PL}%{P0} [@{B}moving mirrors@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor praesidium magus)'" spell_473 = /substitute -p -- %{PL}%{P0} [@{B}mystic bulwark@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(magus foramen)'" spell_474 = /substitute -p -- %{PL}%{P0} [@{B}mystic impairment@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(kratam si feras)'" spell_475 = /substitute -p -- %{PL}%{P0} [@{B}nature's portal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rewat si ruyo nerfdi)'" spell_476 = /substitute -p -- %{PL}%{P0} [@{B}neptune's blessing@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio thorex pois)'" spell_477 = /substitute -p -- %{PL}%{P0} [@{B}neutralize blade@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihuzziw nuubie)'" spell_478 = /substitute -p -- %{PL}%{P0} [@{B}newbie wizheal@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(lluoy tcahc uroy hadte)'" spell_479 = /substitute -p -- %{PL}%{P0} [@{B}northwind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(poistaos moroon)'" spell_480 = /substitute -p -- %{PL}%{P0} [@{B}nullify curse@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tca'n ese stih)'" spell_481 = /substitute -p -- %{PL}%{P0} [@{B}obscurement@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nwod animatsi)'" spell_482 = /substitute -p -- %{PL}%{P0} [@{B}pain@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(freeeeeeeezzzzzdem)'" spell_483 = /substitute -p -- %{PL}%{P0} [@{B}paralyze@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Diordna dionarap)'" spell_484 = /substitute -p -- %{PL}%{P0} [@{B}paranoia@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(jummp noisnemid ehla partyx)'" spell_485 = /substitute -p -- %{PL}%{P0} [@{B}party summon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(PAN AM)'" spell_486 = /substitute -p -- %{PL}%{P0} [@{B}party teleport with error@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(FINNAIR FINNAIR)'" spell_487 = /substitute -p -- %{PL}%{P0} [@{B}party teleport@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tsalpn rea vheewyerre)'" spell_488 = /substitute -p -- %{PL}%{P0} [@{B}pass plant@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(phho samani)'" spell_489 = /substitute -p -- %{PL}%{P0} [@{B}phantom armour@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(waakka wakka)'" spell_490 = /substitute -p -- %{PL}%{P0} [@{B}phantom steed@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(energize)'" spell_491 = /substitute -p -- %{PL}%{P0} [@{B}phaze object@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(armie arma geddon)'" spell_492 = /substitute -p -- %{PL}%{P0} [@{B}phaze shift@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn lotsa phys)'" spell_493 = /substitute -p -- %{PL}%{P0} [@{B}physical preference@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(norbitz lotsa phys)'" spell_494 = /substitute -p -- %{PL}%{P0} [@{B}physical vulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(glaaaash fleeeesssh)'" spell_495 = /substitute -p -- %{PL}%{P0} [@{B}pieni invisibility@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Voidizzzz Pigeonzzz)'" spell_496 = /substitute -p -- %{PL}%{P0} [@{B}pigeon trick@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dimenxsioz azylum)'" spell_497 = /substitute -p -- %{PL}%{P0} [@{B}planar rescue@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Nzghaa kraaii krioo)'" spell_498 = /substitute -p -- %{PL}%{P0} [@{B}plane of dead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tsalpn rea vheewyerre shenot)'" spell_499 = /substitute -p -- %{PL}%{P0} [@{B}plant door@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio thorex poison)'" spell_500 = /substitute -p -- %{PL}%{P0} [@{B}poison blade@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(SAUGIII nyt mua pierettaa)'" spell_501 = /substitute -p -- %{PL}%{P0} [@{B}poison cloud@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor desino toxicum)'" spell_502 = /substitute -p -- %{PL}%{P0} [@{B}poison fend@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lobbrn snake biit)'" spell_503 = /substitute -p -- %{PL}%{P0} [@{B}poison preference@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(norbitz snake biit)'" spell_504 = /substitute -p -- %{PL}%{P0} [@{B}poison vulnerability@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(saugiii)'" spell_505 = /substitute -p -- %{PL}%{P0} [@{B}poison@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Poisonzzzz Pigeonzzz)'" spell_506 = /substitute -p -- %{PL}%{P0} [@{B}poisonous pigeons@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(raza bragh)'" spell_507 = /substitute -p -- %{PL}%{P0} [@{B}power blast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Transferum undeadis poweras)'" spell_508 = /substitute -p -- %{PL}%{P0} [@{B}power transfer@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Ch'ra smarai deathhh)'" spell_509 = /substitute -p -- %{PL}%{P0} [@{B}power word@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Volumetta hcuot tnod)'" spell_510 = /substitute -p -- %{PL}%{P0} [@{B}preparation of harmony@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kaltcorpore brrrhhh)'" spell_511 = /substitute -p -- %{PL}%{P0} [@{B}preservation@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(caa cai cyyrola)'" spell_512 = /substitute -p -- %{PL}%{P0} [@{B}prismatic spray@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(tegntig durben sruht)'" spell_513 = /substitute -p -- %{PL}%{P0} [@{B}produce fire@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(psiaaaa)'" spell_514 = /substitute -p -- %{PL}%{P0} [@{B}project force@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(FAEON PHAXIUS)'" spell_515 = /substitute -p -- %{PL}%{P0} [@{B}protection from evil@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Mortius Dhemcus Shizz)'" spell_516 = /substitute -p -- %{PL}%{P0} [@{B}protection from good@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(olw taf gihh biref)'" spell_517 = /substitute -p -- %{PL}%{P0} [@{B}provision@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Mistress of Water, lend me your power)'" spell_518 = /substitute -p -- %{PL}%{P0} [@{B}psalm of healing@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(sparang psipum)'" spell_519 = /substitute -p -- %{PL}%{P0} [@{B}psionic blast@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(norbitz psycho nydleihs)'" spell_520 = /substitute -p -- %{PL}%{P0} [@{B}psionic vulnerability@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major animus contego)'" spell_521 = /substitute -p -- %{PL}%{P0} [@{B}psychic aegis@{n}]%{PR}
/def -Fp5 -P1BCblue -mregexp -t"'(tora tora TORA)'" spell_522 = /substitute -p -- %{PL}%{P0} [@{B}psychic crush@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(rehwe ser'teh ifre ser'teh kemso)'" spell_523 = /substitute -p -- %{PL}%{P0} [@{B}pyrotechnics@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Uuands snetzk amtui\\?)'" spell_524 = /substitute -p -- %{PL}%{P0} [@{B}question unholiness@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Gnaaahss raaag wwwar)'" spell_525 = /substitute -p -- %{PL}%{P0} [@{B}raise dead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lihaa satunnaisesti lakoon)'" spell_526 = /substitute -p -- %{PL}%{P0} [@{B}random reincarnation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihmodnar)'" spell_527 = /substitute -p -- %{PL}%{P0} [@{B}random wizheal@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(spero candeo forem)'" spell_528 = /substitute -p -- %{PL}%{P0} [@{B}ray of enervation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio enox damage)'" spell_529 = /substitute -p -- %{PL}%{P0} [@{B}razor edge@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Raaaaaiisee thoo roonhs)'" spell_530 = /substitute -p -- %{PL}%{P0} [@{B}reanimate flesh golem@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Grrrrruuuuuhm daaaaath brrriiiiiiiiirth)'" spell_531 = /substitute -p -- %{PL}%{P0} [@{B}reanimate frankenstein@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Raaaaaiisee booneees)'" spell_532 = /substitute -p -- %{PL}%{P0} [@{B}reanimate skeleton@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Raaaaaiisee daawiggh)'" spell_533 = /substitute -p -- %{PL}%{P0} [@{B}reanimate wight@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Raaaaaiisee liinxx)'" spell_534 = /substitute -p -- %{PL}%{P0} [@{B}reanimate zombie@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor obex flamma)'" spell_535 = /substitute -p -- %{PL}%{P0} [@{B}rebuke of ice@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Demonix Perxelex takax tulemax)'" spell_536 = /substitute -p -- %{PL}%{P0} [@{B}recall demon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(DEMONI TAKAS)'" spell_537 = /substitute -p -- %{PL}%{P0} [@{B}recall hunter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Unthon do uuands)'" spell_538 = /substitute -p -- %{PL}%{P0} [@{B}recall undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(laixu duqiz micromachines)'" spell_539 = /substitute -p -- %{PL}%{P0} [@{B}reduce weapon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(BOING booooooiiiiiiing)'" spell_540 = /substitute -p -- %{PL}%{P0} [@{B}reflector shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pu deepsi)'" spell_541 = /substitute -p -- %{PL}%{P0} [@{B}regeneration@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(lihaa lakoon)'" spell_542 = /substitute -p -- %{PL}%{P0} [@{B}reincarnation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ja maisemat vaihtuu)'" spell_543 = /substitute -p -- %{PL}%{P0} [@{B}relocate@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(cado tectum)'" spell_544 = /substitute -p -- %{PL}%{P0} [@{B}remove invulnerabilities@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yawa snluvni rouy ekat I)'" spell_545 = /substitute -p -- %{PL}%{P0} [@{B}remove invulns@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(na saugiii)'" spell_546 = /substitute -p -- %{PL}%{P0} [@{B}remove poison@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(enodnu retaews)'" spell_547 = /substitute -p -- %{PL}%{P0} [@{B}remove preference@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pretty boy)'" spell_548 = /substitute -p -- %{PL}%{P0} [@{B}remove scar@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(idomui ritavi toohai)'" spell_549 = /substitute -p -- %{PL}%{P0} [@{B}remove werecurse@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Antif retteb ouy)'" spell_550 = /substitute -p -- %{PL}%{P0} [@{B}resist disease@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ON Selppa)'" spell_551 = /substitute -p -- %{PL}%{P0} [@{B}resist heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Antif na Saugii)'" spell_552 = /substitute -p -- %{PL}%{P0} [@{B}resist poison@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major auxilium aquilo)'" spell_553 = /substitute -p -- %{PL}%{P0} [@{B}resist void@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ra-ra-raa-raa)'" spell_554 = /substitute -p -- %{PL}%{P0} [@{B}restore memory@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(kaorc kaorc)'" spell_555 = /substitute -p -- %{PL}%{P0} [@{B}restore@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(henget uusix)'" spell_556 = /substitute -p -- %{PL}%{P0} [@{B}resurrect@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yast lstli ro ide)'" spell_557 = /substitute -p -- %{PL}%{P0} [@{B}rock to mud@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa sdratsab nettor)'" spell_558 = /substitute -p -- %{PL}%{P0} [@{B}rotten bastards wizheal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(dhlordz hengeh meniuusiks)'" spell_559 = /substitute -p -- %{PL}%{P0} [@{B}sacred ritual@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(WOObegoneeee NANoo)'" spell_560 = /substitute -p -- %{PL}%{P0} [@{B}sanctuary@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hiilaappa iliihatnas)'" spell_561 = /substitute -p -- %{PL}%{P0} [@{B}santa's heal all@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(They'll never take\\.\\.\\. our FREEDOM!)'" spell_562 = /substitute -p -- %{PL}%{P0} [@{B}score of the steadfast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz Inxtelzhix)'" spell_563 = /substitute -p -- %{PL}%{P0} [@{B}screaming mind@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(jaaagggggwwaaarrrr exxx jaaay twweellllvvv)'" spell_564 = /substitute -p -- %{PL}%{P0} [@{B}see invisible@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(pooftah)'" spell_565 = /substitute -p -- %{PL}%{P0} [@{B}see magic@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(musonm rofth rofuoy tokwon! lesidneg gwor lesidneg gwor!)'" spell_566 = /substitute -p -- %{PL}%{P0} [@{B}seedling@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(zsucker puunch)'" spell_567 = /substitute -p -- %{PL}%{P0} [@{B}sensory overload@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(clips-clips)'" spell_568 = /substitute -p -- %{PL}%{P0} [@{B}sever link@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ru paul)'" spell_569 = /substitute -p -- %{PL}%{P0} [@{B}sex change@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Driadran shadowee shadowee s'dras)'" spell_570 = /substitute -p -- %{PL}%{P0} [@{B}shadow shield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Hakzz anzz slazzh)'" spell_571 = /substitute -p -- %{PL}%{P0} [@{B}sharp nails@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(wanna beeaaaloonne)'" spell_572 = /substitute -p -- %{PL}%{P0} [@{B}shelter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(fulcrathis rae halzuth)'" spell_573 = /substitute -p -- %{PL}%{P0} [@{B}shield of brilliance@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(vis aversor)'" spell_574 = /substitute -p -- %{PL}%{P0} [@{B}shield of protection@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(maximus defenso regis)'" spell_575 = /substitute -p -- %{PL}%{P0} [@{B}shield of the archons@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Shiasha daimyo)'" spell_576 = /substitute -p -- %{PL}%{P0} [@{B}shizen@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(schg trhu bdyr)'" spell_577 = /substitute -p -- %{PL}%{P0} [@{B}shocking grasp@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(titityy)'" spell_578 = /substitute -p -- %{PL}%{P0} [@{B}shop check@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(ARRRRRRRRRRRRRGGGGGGHHHHH!!!)'" spell_579 = /substitute -p -- %{PL}%{P0} [@{B}shriek@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio enox class)'" spell_580 = /substitute -p -- %{PL}%{P0} [@{B}silver sheen@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tis u dyr teha)'" spell_581 = /substitute -p -- %{PL}%{P0} [@{B}sirocco@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(ays eeshec)'" spell_582 = /substitute -p -- %{PL}%{P0} [@{B}skyfire@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Eat lag muthafuck!)'" spell_583 = /substitute -p -- %{PL}%{P0} [@{B}slow person@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(slo saugiii)'" spell_584 = /substitute -p -- %{PL}%{P0} [@{B}slow poison@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Noooooo\\.\\.sanityyyhhhh!)'" spell_585 = /substitute -p -- %{PL}%{P0} [@{B}slow@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(DAMN ITS COLD!)'" spell_586 = /substitute -p -- %{PL}%{P0} [@{B}snowstorm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(The source of all magic!)'" spell_587 = /substitute -p -- %{PL}%{P0} [@{B}sonata of sorcery@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(I can barely see you now\\.\\.\\.)'" spell_588 = /substitute -p -- %{PL}%{P0} [@{B}song of celerity@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Anybody got a scalpel\\?)'" spell_589 = /substitute -p -- %{PL}%{P0} [@{B}song of mending@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(thea pede)'" spell_590 = /substitute -p -- %{PL}%{P0} [@{B}soothing heat@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Shiand drygh aurn)'" spell_591 = /substitute -p -- %{PL}%{P0} [@{B}soul fusion@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Shiand aurn)'" spell_592 = /substitute -p -- %{PL}%{P0} [@{B}soul merge@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(eraahs stheel)'" spell_593 = /substitute -p -- %{PL}%{P0} [@{B}soul transfer@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(prgh burtsh)'" spell_594 = /substitute -p -- %{PL}%{P0} [@{B}soul wrack@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Sssuuuck soulis)'" spell_595 = /substitute -p -- %{PL}%{P0} [@{B}soulsuck@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(zruphture cspace)'" spell_596 = /substitute -p -- %{PL}%{P0} [@{B}spacial barrier@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor tutamen caelum)'" spell_597 = /substitute -p -- %{PL}%{P0} [@{B}spark shelter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tolvaris tulhani sulharic)'" spell_598 = /substitute -p -- %{PL}%{P0} [@{B}spellshield@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(orbis inflo abrogo)'" spell_599 = /substitute -p -- %{PL}%{P0} [@{B}sphere of dismantling@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(wonit thunatre tsirpi)'" spell_600 = /substitute -p -- %{PL}%{P0} [@{B}spirit of nature@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Decha powella invirtis lucerne)'" spell_601 = /substitute -p -- %{PL}%{P0} [@{B}spiritual hammer@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ne lux HOL)'" spell_602 = /substitute -p -- %{PL}%{P0} [@{B}staff light@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(rhasrep hatn u nertesps ttoho)'" spell_603 = /substitute -p -- %{PL}%{P0} [@{B}sticks to snakes@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Juu aar nou longer zztoned)'" spell_604 = /substitute -p -- %{PL}%{P0} [@{B}stone to flesh@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ommm morin granitia)'" spell_605 = /substitute -p -- %{PL}%{P0} [@{B}stonefist@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(leeadd iinnn yyyrrr sshhoooeeezz)'" spell_606 = /substitute -p -- %{PL}%{P0} [@{B}stoneshoes@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(yargolgse ta gnormin)'" spell_607 = /substitute -p -- %{PL}%{P0} [@{B}stoneskin@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(SIIIIILEEEEEEENCE)'" spell_608 = /substitute -p -- %{PL}%{P0} [@{B}storm of silence@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Boom Bap)'" spell_609 = /substitute -p -- %{PL}%{P0} [@{B}stun resistance@{n}]%{PR}
/def -Fp5 -P1BCwhite -mregexp -t"'(Haer haer sharakam dasta)'" spell_610 = /substitute -p -- %{PL}%{P0} [@{B}suffocation@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Naaakh rhazhin)'" spell_611 = /substitute -p -- %{PL}%{P0} [@{B}summon aide@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(loky leky laky)'" spell_612 = /substitute -p -- %{PL}%{P0} [@{B}summon animus@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Baggius Maximus)'" spell_613 = /substitute -p -- %{PL}%{P0} [@{B}summon bag of holding@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Grr Grrro Grrroooommm)'" spell_614 = /substitute -p -- %{PL}%{P0} [@{B}summon bear@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Thazzzzrr kurmaaax TO!)'" spell_615 = /substitute -p -- %{PL}%{P0} [@{B}summon demonic servant@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Devonizzzzz ASGARTH!!! dahzzz)'" spell_616 = /substitute -p -- %{PL}%{P0} [@{B}summon devil@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Flap Flaaap Fllaaapp)'" spell_617 = /substitute -p -- %{PL}%{P0} [@{B}summon eagle@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(sit-ubu-sit)'" spell_618 = /substitute -p -- %{PL}%{P0} [@{B}summon familiar@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sshhh Shhhwwoosh)'" spell_619 = /substitute -p -- %{PL}%{P0} [@{B}summon fire drake@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Jundh Dheax menxix)'" spell_620 = /substitute -p -- %{PL}%{P0} [@{B}summon ghost@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Devonizzzzz XANTHARG!!! archdazzzz)'" spell_621 = /substitute -p -- %{PL}%{P0} [@{B}summon greater demon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sumohn makxsimush demonicus)'" spell_622 = /substitute -p -- %{PL}%{P0} [@{B}summon greater hunter@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(shroom vacuum)'" spell_623 = /substitute -p -- %{PL}%{P0} [@{B}summon greater spores@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rulle-rull)'" spell_624 = /substitute -p -- %{PL}%{P0} [@{B}summon greater wheelchair@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Griaaan uuands)'" spell_625 = /substitute -p -- %{PL}%{P0} [@{B}summon horde@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(Iiaca brr amny icem)'" spell_626 = /substitute -p -- %{PL}%{P0} [@{B}summon icicles@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(payr rof u gbu thilg)'" spell_627 = /substitute -p -- %{PL}%{P0} [@{B}summon insects@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(jugglex fugglex)'" spell_628 = /substitute -p -- %{PL}%{P0} [@{B}summon juggling torch@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sumohn lhesheritus demonicus)'" spell_629 = /substitute -p -- %{PL}%{P0} [@{B}summon lesser hunter@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(shroom broom)'" spell_630 = /substitute -p -- %{PL}%{P0} [@{B}summon lesser spores@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(teletapit kotiin, teletapit kotiin!)'" spell_631 = /substitute -p -- %{PL}%{P0} [@{B}summon minions@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sumohn mihnoritus demonicus')'" spell_632 = /substitute -p -- %{PL}%{P0} [@{B}summon minor hunter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sumohn mihnoritus demonicus)'" spell_633 = /substitute -p -- %{PL}%{P0} [@{B}summon minor hunter@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Thazzzzrr grumaaaz TO!)'" spell_634 = /substitute -p -- %{PL}%{P0} [@{B}summon moomin@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(floowl eth rotarc sealpe)'" spell_635 = /substitute -p -- %{PL}%{P0} [@{B}summon mule@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Kra's dras shaidon)'" spell_636 = /substitute -p -- %{PL}%{P0} [@{B}summon orb of reflection@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(sumting worse dan dakstaf)'" spell_637 = /substitute -p -- %{PL}%{P0} [@{B}summon phantom beast@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(aAl-louchszz mme to wriip phleeshhhh)'" spell_638 = /substitute -p -- %{PL}%{P0} [@{B}summon phantom sickle@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(pelh sumon)'" spell_639 = /substitute -p -- %{PL}%{P0} [@{B}summon phantom warriors@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Awop-Bop-a-Loobop-Awop-Bam-Boom)'" spell_640 = /substitute -p -- %{PL}%{P0} [@{B}summon psisword@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Griaaan raaag)'" spell_641 = /substitute -p -- %{PL}%{P0} [@{B}summon servant@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(A'rdas shadowas rais)'" spell_642 = /substitute -p -- %{PL}%{P0} [@{B}summon shadow@{n}]%{PR}
/def -Fp5 -P1BCcyan -mregexp -t"'(gunpul teh palniescap)'" spell_643 = /substitute -p -- %{PL}%{P0} [@{B}summon storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Yaaaarrrgetoffamyfaceyoubassstarrrdddss!)'" spell_644 = /substitute -p -- %{PL}%{P0} [@{B}summon super sparkley pony storm@{n}]%{PR}
/def -Fp5 -P1Cyellow -mregexp -t"'(tge em meso dira)'" spell_645 = /substitute -p -- %{PL}%{P0} [@{B}summon swarm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Miii Miiiaaa Miiaauuww)'" spell_646 = /substitute -p -- %{PL}%{P0} [@{B}summon wild cat@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sumooon daa wiiil oo miist)'" spell_647 = /substitute -p -- %{PL}%{P0} [@{B}summon will o' mist@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Aaa Aaaooowww)'" spell_648 = /substitute -p -- %{PL}%{P0} [@{B}summon wolf@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(jummp noisnemid)'" spell_649 = /substitute -p -- %{PL}%{P0} [@{B}summon@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(sendraks nca nto cefa eth ghilt)'" spell_650 = /substitute -p -- %{PL}%{P0} [@{B}sunray@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(What's this bit for\\?)'" spell_651 = /substitute -p -- %{PL}%{P0} [@{B}surgeon's chant@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(TAP the wide open plains to stop the folly of war!)'" spell_652 = /substitute -p -- %{PL}%{P0} [@{B}swords to plowshares@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(We shall split the baby in twain)'" spell_653 = /substitute -p -- %{PL}%{P0} [@{B}symphony of solomon@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(First you see it, then you don't, then you do!)'" spell_654 = /substitute -p -- %{PL}%{P0} [@{B}tale of perception@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(modirma zalas)'" spell_655 = /substitute -p -- %{PL}%{P0} [@{B}telekinetic barrier@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihisp)'" spell_656 = /substitute -p -- %{PL}%{P0} [@{B}telepathic heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(fuei qopea)'" spell_657 = /substitute -p -- %{PL}%{P0} [@{B}teleport with error@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ne err fuei qopea)'" spell_658 = /substitute -p -- %{PL}%{P0} [@{B}teleport without error@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio drag moooooor eeeeviil)'" spell_659 = /substitute -p -- %{PL}%{P0} [@{B}tenrai blade@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(BOOOOOOO!!!!)'" spell_660 = /substitute -p -- %{PL}%{P0} [@{B}terror@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(racha on pun lon cordso jompon)'" spell_661 = /substitute -p -- %{PL}%{P0} [@{B}thorn spray@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(hte aorr fo nehrudt slilf eth ria)'" spell_662 = /substitute -p -- %{PL}%{P0} [@{B}thunderclap@{n}]%{PR}
/def -Fp5 -P1BCred -mregexp -t"'(rfo lal ghsint u essoan)'" spell_663 = /substitute -p -- %{PL}%{P0} [@{B}time's arrow@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Darkness\\?  Shadows\\?  BEGONE!)'" spell_664 = /substitute -p -- %{PL}%{P0} [@{B}torchbearer's march@{n}]%{PR}
/def -Fp5 -P1BCblack -mregexp -t"'(Uoy Eltrut)'" spell_665 = /substitute -p -- %{PL}%{P0} [@{B}tortoise nervosa@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tannic mazhol)'" spell_666 = /substitute -p -- %{PL}%{P0} [@{B}totem of light@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(Darkenna soulus)'" spell_667 = /substitute -p -- %{PL}%{P0} [@{B}touch of darkness@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Dazidarom deathee gradas)'" spell_668 = /substitute -p -- %{PL}%{P0} [@{B}touch of death@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(niapym ekat)'" spell_669 = /substitute -p -- %{PL}%{P0} [@{B}transfer damage@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Sruoy si, enim si tahw)'" spell_670 = /substitute -p -- %{PL}%{P0} [@{B}transfer mana@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(BurrR froost vycolDd in a distance!)'" spell_671 = /substitute -p -- %{PL}%{P0} [@{B}true distant blizzard storm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(struh yawa yelurti)'" spell_672 = /substitute -p -- %{PL}%{P0} [@{B}true distant heal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(nap iag oog oom)'" spell_673 = /substitute -p -- %{PL}%{P0} [@{B}true distant resurrect@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(ronimuoy ootem)'" spell_674 = /substitute -p -- %{PL}%{P0} [@{B}true distant transfer@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(niapym ekat WON)'" spell_675 = /substitute -p -- %{PL}%{P0} [@{B}true transfer damage@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Ooo the pain of it all)'" spell_676 = /substitute -p -- %{PL}%{P0} [@{B}true transfer@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tola pu animatsi)'" spell_677 = /substitute -p -- %{PL}%{P0} [@{B}true unpain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(eth doog lilw sphire)'" spell_678 = /substitute -p -- %{PL}%{P0} [@{B}unbeliever's doom@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(eth ilev lilw sphire)'" spell_679 = /substitute -p -- %{PL}%{P0} [@{B}unbeliever's doom@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(rautasahaa)'" spell_680 = /substitute -p -- %{PL}%{P0} [@{B}unchain@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Merciah)'" spell_681 = /substitute -p -- %{PL}%{P0} [@{B}unholy absolution@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Uuands nostunnzz)'" spell_682 = /substitute -p -- %{PL}%{P0} [@{B}unholy courage@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Blesiorum death chantee ivyle)'" spell_683 = /substitute -p -- %{PL}%{P0} [@{B}unholy gift@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Uuands snetzk TAUR!)'" spell_684 = /substitute -p -- %{PL}%{P0} [@{B}unholy power@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(graaahm)'" spell_685 = /substitute -p -- %{PL}%{P0} [@{B}unholy presence@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Uuands snetzk HOAR!)'" spell_686 = /substitute -p -- %{PL}%{P0} [@{B}unholy strength@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(You can doooo eeeeeet!)'" spell_687 = /substitute -p -- %{PL}%{P0} [@{B}uplifting melody@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(daimio drag moooooor)'" spell_688 = /substitute -p -- %{PL}%{P0} [@{B}vaporic blade@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major claudo toxicum)'" spell_689 = /substitute -p -- %{PL}%{P0} [@{B}venom fend@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(And a young man for all time ye shall be\\.)'" spell_690 = /substitute -p -- %{PL}%{P0} [@{B}venril's verses of vitality@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor prohibeo algidum)'" spell_691 = /substitute -p -- %{PL}%{P0} [@{B}vestment of flame@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Forget tomorrow, live now!  FIGHT FIGHT FIGHT!)'" spell_692 = /substitute -p -- %{PL}%{P0} [@{B}vigorous concerto@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(You can see it clearly)'" spell_693 = /substitute -p -- %{PL}%{P0} [@{B}visualize act@{n}]%{PR}
/def -Fp5 -P1Cgreen -mregexp -t"'(macilentus corium)'" spell_694 = /substitute -p -- %{PL}%{P0} [@{B}vitriolic bane@{n}]%{PR}
/def -Fp5 -P1Cblue -mregexp -t"'(screeeeeamhh)'" spell_695 = /substitute -p -- %{PL}%{P0} [@{B}wail of banshee@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(cwath hte lefmas nadec)'" spell_696 = /substitute -p -- %{PL}%{P0} [@{B}wall of fire@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(oyu ranet vanlieg rhee noso)'" spell_697 = /substitute -p -- %{PL}%{P0} [@{B}wall of thorns@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major patronus ferratus)'" spell_698 = /substitute -p -- %{PL}%{P0} [@{B}ward of steel@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(minor patronus saxum)'" spell_699 = /substitute -p -- %{PL}%{P0} [@{B}ward of stone@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(juciadious gradalt)'" spell_700 = /substitute -p -- %{PL}%{P0} [@{B}ward undead@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Cruzxh dz hxitzpregpx)'" spell_701 = /substitute -p -- %{PL}%{P0} [@{B}warriors bane@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(mal tulvaro tulmaro)'" spell_702 = /substitute -p -- %{PL}%{P0} [@{B}water breathing@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Jeeeeeeesuuuuuuuuuuuuuuuuus)'" spell_703 = /substitute -p -- %{PL}%{P0} [@{B}water walking@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Czruxh dz Stxreknz)'" spell_704 = /substitute -p -- %{PL}%{P0} [@{B}weary arms@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Chiiiildren of the Night)'" spell_705 = /substitute -p -- %{PL}%{P0} [@{B}were curse@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(gluuw bwal)'" spell_706 = /substitute -p -- %{PL}%{P0} [@{B}white orb@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(And the goose flew away from the hunter\\.)'" spell_707 = /substitute -p -- %{PL}%{P0} [@{B}wild goose@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Wilwarin toa esca niarath Eliendien)'" spell_708 = /substitute -p -- %{PL}%{P0} [@{B}wilwarin@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(major obex incendia)'" spell_709 = /substitute -p -- %{PL}%{P0} [@{B}winter's rebuke@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(helbub cesap eopesclet)'" spell_710 = /substitute -p -- %{PL}%{P0} [@{B}wisdom of ptah@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Undarus sam hades)'" spell_711 = /substitute -p -- %{PL}%{P0} [@{B}wither@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(raptus regaliter)'" spell_712 = /substitute -p -- %{PL}%{P0} [@{B}wiz anti-bless@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(die dulci fruere)'" spell_713 = /substitute -p -- %{PL}%{P0} [@{B}wizbless@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihyssivomoh)'" spell_714 = /substitute -p -- %{PL}%{P0} [@{B}wizharm@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(healaappa iliihuzziw)'" spell_715 = /substitute -p -- %{PL}%{P0} [@{B}wizheal@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(Hoppers vision)'" spell_716 = /substitute -p -- %{PL}%{P0} [@{B}wolf eyes@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(chi-chi-chicken)'" spell_717 = /substitute -p -- %{PL}%{P0} [@{B}word of recall@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(veehalyn gaer)'" spell_718 = /substitute -p -- %{PL}%{P0} [@{B}wrath of gabriel@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(veehalyn gaer\\.)'" spell_719 = /substitute -p -- %{PL}%{P0} [@{B}wrath of gabriel@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(veehalyn yurf)'" spell_720 = /substitute -p -- %{PL}%{P0} [@{B}wrath of god@{n}]%{PR}
/def -Fp5 -P1BCmagenta -mregexp -t"'(veehalyn yurf\\.)'" spell_721 = /substitute -p -- %{PL}%{P0} [@{B}wrath of god@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(uuseoqa nuliosto)'" spell_722 = /substitute -p -- %{PL}%{P0} [@{B}wrath of tefnut@{n}]%{PR}
/def -Fp5 -P1 -mregexp -t"'(tannic zhol)'" spell_723 = /substitute -p -- %{PL}%{P0} [@{B}wyvern watch@{n}]%{PR}
